-- SQLite
CREATE TABLE Files (
    FileID INTEGER PRIMARY KEY AUTOINCREMENT,
    Filename VARCHAR(255) NOT NULL,
    Size BIGINT NOT NULL,
    ContentType VARCHAR(50) NOT NULL,
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);